plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.kspotting' // DEVE corrispondere al tuo package name
    compileSdk 34

    defaultConfig {
        applicationId "com.example.kspotting" // DEVE corrispondere al tuo package name
        minSdk 26 // ESSENZIALE: minSdk 26 per compatibilità API e icone adattive
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    aaptOptions {
        noCompress "tflite" // Assicurati che il modello TFLite non venga compresso
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.cardview:cardview:1.0.0'


    // TensorFlow Lite dependencies - Core e Task Audio
    implementation 'org.tensorflow:tensorflow-lite:2.15.0'
    implementation 'org.tensorflow:tensorflow-lite-task-audio:0.4.4'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.4'
    implementation 'org.tensorflow:tensorflow-lite-task-base:0.4.4'

    // NUOVA DIPENDENZA: Local Broadcast Manager per la comunicazione Service-Activity
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
